### PR TITLE
Basic object model implemented

### PR DESCRIPTION
**Pull request by a-schild**
This pull request changes these things:
- Requires php 7.1+
- getMasterData(), getCalendarEvents() and getAllEventData() return objects of the corresponding types

Not all values from the api are yet transformed into objects.
Missing is the getAllPersonData() from the RestApi class. Since I don't need it at them moment, I havent yet worked on it

### CODE REVIEW

**Comment by a-schild** [comment]
Hello,

could you please merge these changes and make a new release of it?
I'm using it in this project https://github.com/a-schild/churchtools-pdfcalendar and would like to reference a version number.

**Comment by YetiCGN** [comment]
I'm not entirely happy with your approach, since I am a fan of POPO entities (Plain Old PHP Objects) without dependencies. These entities are highly specific only to be created by the API reader, for example I miss all the setters.
I hope I have time this weekend to think about a solution I like more that's still API-compatible with your project.

But thanks a lot nonetheless for contributing!

**Comment by a-schild** [comment]
Yes, i know that we would also need all setters.
But since the API is currently used in readonly I think this isn't that big limitation.

Anyway in the future the REST api of ct will be the way to go, so the question is, how much effort we still invest in this API.
They have not mentioned a time frame, but I think by end of the year we will have most parts available via REST, and then we can stop this project

**Comment by YetiCGN** [comment]
Huh, interesting. I didn't know that.

**Comment by a-schild** [comment]
https://forum.church.tools/topic/5121/restful-api-vorstellung/11

They need it to implement the mobile app.
So they are reworking the whole thing to be available via REST, step by step.

**Comment by YetiCGN** [comment]
OK, great! Still, this could be useful as a wrapper so people don't have to implement all the REST calls they need. If only I had plenty of time... 😉

**Pull request merged**
